version: "3.7"

services:
  sfu-origin:
    image: eyevinntechnology/wrtc-sfu:v0.3.0
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
    environment:
      - HTTP_PORT=8080
      - UDP_PORT=12000
      - IPV4_ADDR=127.0.0.1
      - API_KEY=dev
    logging:
      driver: "local"
      options:
        max-size: 10m
    ports:
      - "8080:8080/tcp"
      - "12000:12000/udp"
  sfu-edge1:
    image: eyevinntechnology/wrtc-sfu:v0.3.0
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
    environment:
      - HTTP_PORT=8081
      - UDP_PORT=13000
      - IPV4_ADDR=127.0.0.1
      - API_KEY=dev
    ports:
      - "8081:8081/tcp"
      - "13000:13000/udp"
    logging:
      driver: "local"
      options:
        max-size: 10m
  sfu-edge2:
    image: eyevinntechnology/wrtc-sfu:v0.3.0
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
    environment:
      - HTTP_PORT=8082
      - UDP_PORT=13001
      - IPV4_ADDR=127.0.0.1
      - API_KEY=dev
    ports:
      - "8082:8082/tcp"
      - "13001:13001/udp"
    logging:
      driver: "local"
      options:
        max-size: 10m
  egress1:
    image: eyevinntechnology/wrtc-whpp:v0.2.0
    environment:
      - PORT=8001
      - EXT_PORT=8001
      - HOSTNAME=localhost
      - SMB_URL=http://sfu-edge1:8081/conferences/
    ports:
      - "8001:8001/tcp"      
  egress2:
    image: eyevinntechnology/wrtc-whpp:v0.2.0
    environment:
      - PORT=8002
      - EXT_PORT=8002
      - HOSTNAME=localhost
      - SMB_URL=http://sfu-edge2:8082/conferences/
    ports:
      - "8002:8002/tcp"      
